"""Add sessions table and session_id to messages

Revision ID: 326c4a3f22ab
Revises: 82f551823293
Create Date: 2025-07-09 12:05:25.932427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326c4a3f22ab'
down_revision: Union[str, None] = '82f551823293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('session_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'session_id')
    op.drop_table('session')
    # ### end Alembic commands ###
