"""Add role and date type fields

Revision ID: 82f551823293
Revises: 
Create Date: 2025-07-09 10:24:31.107195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f551823293'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_type'), 'messages', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_type'), table_name='messages')
    op.drop_column('messages', 'type')
    op.drop_column('messages', 'date')
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###
